name: PublishToDockerhub

on:
  push:
    tags:
      - 'v*'
    #branches:
    #  - main

jobs:
  publish-to-dockerhub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.9.0
      - name: Install Yarn Packages
        run: |
          docker image prune -a -f
          sudo -E apt-get -qq autoremove --purge
          cd webui
          yarn install
      - name: Build Webui
        run: |
          cd webui
          yarn run build
          rm -fr node_modules
          cd ..
          sed -i "s/Vue App/KubeFileBrowser/g" static/index.html
      - name: Install go
        uses: actions/setup-go@v3
        with:
          go-version: '>=1.18.0'
      - name: Build Kftools
        run: |
          sudo apt-get update
          sudo apt-get install upx musl-dev git -y
          chmod +x 00-build_lib.sh
          ./00-build_lib.sh
      - name: Get tag name
        uses: olegtarasov/get-tag@v2.1
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          dockerfile: Dockerfile
          platforms: linux/arm/v6,linux/arm/v7,linux/arm/v8,linux/arm64,linux/amd64,linux/386,linux/ppc64le,linux/s390x
          push: true
          tags: |
            xmapst/kubefilebrowser:latest
            xmapst/kubefilebrowser:${{ env.GIT_TAG_NAME }}
